categories = [
     'Atelectasis',
     'Cardiomegaly',
     'Consolidation',
     'Edema',
     'Enlarged Cardiomediastinum',
     'Fracture',
     'Lung Lesion',
     'Lung Opacity',
     'No Finding',
     'Pleural Effusion',
     'Pleural Other',
     'Pneumonia',
     'Pneumothorax',
     'Support Devices',
     'Atelectasis_cx',
     'Cardiomegaly_cx',
     'Consolidation_cx',
     'Edema_cx',
     'Enlarged Cardiomediastinum_cx',
     'Fracture_cx',
     'Lung Lesion_cx',
     'Lung Opacity_cx',
     'No Finding_cx',
     'Pleural Effusion_cx',
     'Pleural Other_cx',
     'Pneumonia_cx',
     'Pneumothorax_cx',
     'Support Devices_cx'
]

medical_dict = [
     'Atelectasis': 'Atelectasis',
     'Cardiomegaly': 'Cardiomegaly',
     'Consolidation': 'Consolidation',
     'Edema':'Edema',
     'Enlarged Cardiomediastinum': 'Enlarged Cardiomediastinum',
     'Fracture': 'Fracture',
     'Lung Lesion' : 'Lung Lesion',
     'Lung Opacity' : 'Lung Opacity',
     'No Finding': 'No Finding',
     'Pleural Effusion': 'Pleural Effusion',
     'Pleural Other': 'Pleural Other',
     'Pneumonia': 'Pneumonia',
     'Pneumothorax': 'Pneumothorax',
     'Support Devices': 'Support Device',
     'Atelectasis_cx': 'Atelectasis',
     'Cardiomegaly_cx': 'Cardiomegaly',
     'Consolidation_cx': ' Consolidation',
     'Edema_cx': 'Edema',
     'Enlarged Cardiomediastinum_cx': 'Enlarged Cardiomediastinum',
     'Fracture_cx': 'Fracture',
     'Lung Lesion_cx': 'Lung Lesion',
     'Lung Opacity_cx': 'Lung Opacity',
     'No Finding_cx': 'No Finding',
     'Pleural Effusion_cx': 'Pleural Effusion',
     'Pleural Other_cx': 'Pleural Anomolay',
     'Pneumonia_cx': 'Pneumonia',
     'Pneumothorax_cx': 'Pneumothorax',
     'Support Devices_cx': 'Support Device'
]